### PR TITLE
Remove trailing whitespace for all file types.

### PR DESCRIPTION
**Pull request by pgr0ss**

### CODE REVIEW

**Comment by pgr0ss** [comment]
I was cleaning up old branches and noticed this. We still list out specific file types instead of doing all of them (and our list has grown). Thoughts on making it a `*`?

**Comment by mattikus** [comment]
I'm generally -1 auto removing whitespace on all files due to the diffs it will create on files that have trailing whitespace. I love the idea and hate trailing whitespace, but I'm not wild about it being automated rather than an explicit action.

**Comment by wjr1985** [comment]
I'm also -1 for similar reasons to @mattikus, plus for some files (especially for fixed width test fixture files) we really don't want to have auto-removed whitespace

**Comment by lollipopman** [comment]
My preference would be to remove this setting, rather than expand it. I find this config frustrating when working with open source code bases. Those code bases often have trailing white space somewhere in their files, which means when I save my commit I have unintentionally introduced extraneous white space changes into my commit, which I then need to back out after disabling this setting.

**Comment by pgr0ss** [comment]
We went the other way: https://github.com/braintreeps/vim_dotfiles/pull/73

**Pull request closed without merging**
