### PR TITLE
Add vim-sensible plugin

### PR DESCRIPTION
**Pull request by jaresty**
# What

Add vim-sensible plugin from tpope.

# Why

We already use several tpope plugins and this one is intended to provide "sensible defaults that everyone can agree on." Who can disagree with that?

### CODE REVIEW

**Comment by jcoleman** [comment]
What settings does this actually change, and which ones are different than what we already use?

**Comment by jaresty** [comment]
The repo for this plugin can be found [here](https://github.com/tpope/vim-sensible).  It falls into the same category (same author, in fact) as many plugins that have been included since the beginning of this repo (https://github.com/braintreeps/vim_dotfiles/blame/cc0249cd4a4ca4199818ce26bf08c446700a4302/vimrc.bundles).  It provides sensible defaults and the author is quite responsive to community feedback.

**Comment by jcoleman** [comment]
I’d found the repo; but I’d like to see a list of what we’re actually changing with this. Otherwise it’s impossible to know if we need it (maybe we already set all the things it sets) or if it changes things we don’t want to change. 

Furthermore even if we do want it, we’d likely want to also remove stuff we’re configuring already that would become duplicative with this plugin.

**Comment by jaresty** [comment]
This is the complete configuration set here as far as I can tell: (https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim).  It's relatively short. I haven't gone through yet to audit/remove the duplicative settings, though I agree that it would make sense to remove them.

**Comment by jaresty** [comment]
Comparing just the `set` commands, these settings are shared:
```
set backspace=indent,eol,start
set incsearch
set laststatus=2
set ruler
```
These are only in vim-sensible:
```
set autoindent
set autoread
set complete-=i
set display+=lastline
set encoding=utf-8
set formatoptions+=j " Delete comment character when joining commented lines
set history=1000
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set nrformats-=octal
set scrolloff=1
set sessionoptions-=options
set shell=/usr/bin/env\ bash
set sidescrolloff=5
set smarttab
set t_Co=16
set tabpagemax=50
set ttimeout
set ttimeoutlen=100
set viewoptions-=options
set viminfo^=!
set wildmenu
setglobal tags-=./tags tags-=./tags; tags^=./tags;
```
These are only in braintree vim:
```
set background=dark
set backupcopy=yes
set complete-=t
set dir=/tmp//
set hidden
set hlsearch
set ignorecase
set mouse=
set nocompatible
set nonu
set number
set scrolloff=5
set shell=/bin/bash
set showmatch
set signcolumn=yes
set smartcase
set statusline+=%-40f\
set statusline+=%1*%y%*%*\
set statusline+=%10(L(%l/%L)%)\
set statusline+=%2(C(%v/125)%)\
set statusline+=%2*[%n%H%M%R%W]%*\
set statusline+=%<\
set statusline+=%=
set statusline+=%P
set statusline=
set tags+=gems.tags
set textwidth=0 nosmartindent tabstop=2 shiftwidth=2 softtabstop=2 expandtab
set ttyfast
set ttymouse=
set undodir=~/.vim/undodir
set undofile
set undolevels=1000
set undoreload=10000
set updatetime=200
set wildignore+=*.pyc,*.o,*.class,*.lo,.git,vendor/*,node_modules/**,bower_components/**,*/build_gradle/*,*/build_intellij/*,*/build/*,*/cassandra_data/*
set wrap
```

**Comment by jaresty** [comment]
For reference on the difference between `set complete-=i` and `set complete-=t` you can read this reference (https://medium.com/usevim/set-complete-e76b9f196f0f).  Our current vim completion settings are `complete=.,w,b,u,i`; running `set complete-=i` removes `i` from that list.  `i` means "search all files that it thinks has been included according to C semantics:" according to that document.  I don't _think_ that will provide valuable completion recommendations in gateway, since it is a ruby code base.  I have found completion in gateway to work pretty badly for me using default completion `^N`; it works better for me if I use tag completion `^X^]` for example.

**Comment by ssgelm** [comment]
FWIW `^N` completion works pretty well in the infra repo currently, though I have no idea if it's from `i`

**Comment by jcoleman** [comment]
Which of those additions or changes do you find to be helpful? And which ones might be impactful/surprising to others?

I don't immediately recognize most of them, though
```
set formatoptions+=j " Delete comment character when joining commented lines
```
looks pretty useful. So for the PR it would be helpful to know what functionality we're gaining (or from someone's perspective possibly losing).

I believe we should have a good reason for why changes are desirable before we have a PR. I'm also concerned that hiding standard options like this in a plugin will make it harder for users to understand how Vim is configured (and where that configuration comes from). So if there are options we feel would be useful then perhaps we should inline them into our config?

**Comment by jaresty** [comment]
To be honest, I wasn't prepared to defend each setting individually.  My understanding of this plugin is that it is intended to provide a non-controversial baseline, kind of like a CSS reset does to avoid quirky differences between browsers.  Many of these settings are turned on by default in neovim, which argues that these defaults make more sense than the current base settings (https://neovim.io/doc/user/vim_diff.html), which leads me to believe that they may also be eventually turned on by default in vim itself. I can relate to the argument that these settings should be discussed, but I also don't believe that the vim defaults themselves would be reviewed if vim were to change them under the hood.  At any rate, I had hoped that this change wouldn't be controversial since it is a relatively well-used plugin, we've already got several by the same author included here, and I think the vim default behavior is not perfect.  I am used to them being turned on in part because I am a neovim user on my own cpair, so the defaults are different anyway.

**Comment by ssgelm** [comment]
@jaresty I completely understand your perspective, but you also have to remember that this is a setup that many of us have been using for 7+ years so even a seemingly innocuous change could be very inconvenient. I think that `vim-sensible` is a great plugin for general "I don't have a config so let's set some defaults" but at both our size and level of customization it's possible that some of the options chosen here may run counter to both people's expectations and to existing choices we have made in our vimrc, so I think the best course of action would be to isolate the settings that are tripping you up and propose just those. My intention here is not to discourage you from trying to improve our vim configs because I think there's a _ton_ of value in doing so. I just wanted to make you aware of why people are more likely to react negatively to a plugin that's a bit of a black box without digging into the source itself.

**Comment by jaresty** [comment]
Since using nvim resolves my issue, I'm going to close this PR.

**Pull request closed without merging**
