### PR TITLE
Revert "Adds async linting and completion choices"

### PR DESCRIPTION
**Pull request by mrak**
Reverts braintreeps/vim_dotfiles#51

In response to https://github.com/braintreeps/vim_dotfiles/pull/51#issuecomment-301515787

### CODE REVIEW

**Comment by drewolson** [comment]
I'm totally fine keeping the package, many folks seem to enjoy it. I'd personally prefer it to be disabled by default, but if others feel differently I'd be ok with keeping things as is.

**Comment by ctso** [comment]
I too was caught off guard by the addition of [completor.vim](https://github.com/maralla/completor.vim), but I'm slowly getting used to it.

However, the addition of [w0rp/ale](https://github.com/w0rp/ale) is 👍 👍 👍 , in my opinion.  I'd rather see us keep that.

**Comment by drewolson** [comment]
Perhaps we should keep the existing behavior and just set:

```let g:ale_lint_on_text_changed = "never"```

For me, the challenging part of the current behavior is the linting of half-typed lines. Again, I don't feel super strongly about it, so feel free to simply keep the existing behavior.

**Comment by ctso** [comment]
I can see how that'd bother you (or anyone, really).  Maybe a good compromise is:

```
let g:ale_lint_on_text_changed = "normal"
let g:ale_lint_on_insert_leave = 1
```

What this says is "lint whenever text is changed in 'normal' mode, and lint whenever leaving insert mode"

**Comment by drewolson** [comment]
@ctso 👍

**Comment by ctso** [comment]
See https://github.com/braintreeps/vim_dotfiles/pull/57

**Comment by mrak** [comment]
Closing in favor of #58

**Pull request closed without merging**
