### PR TITLE
Remove gvimrc

### PR DESCRIPTION
**Pull request by pgr0ss**
# What

Remove `.gvimrc`.

# Why

It doesn't seem like anyone uses gvim anymore and this file hasn'tchanged since 2011.

# Checklist

- [ ] ~Send RFC email to Braintree developers _if change may be impactful_. Please include a link to this PR so that disucssion about the pros and cons of the change remains linked to the proposed changes.~ This does not seem impactful.

### CODE REVIEW

**Comment by ClashTheBunny** [comment]
I think you would also want to remove it from the README and the activate.sh script.

**Comment by ClashTheBunny** [comment]
Also, I do tend to not use gvim, but there are people who prefer gvim to macvim.  Is it harmless to leave this here?  Did you test it to be broken, or is it just worry about bit-rot?

**Comment by pgr0ss** [comment]
@ClashTheBunny I was just trying to clean up unused things. Given that no one has iterated on it since 2011, I was thinking probably no one was using it.

**Comment by pgr0ss** [comment]
> I think you would also want to remove it from the README and the activate.sh script.

4f22c8c

**Pull request merged**
