### PR TITLE
Switch fuzzy finding from CtrlP to fzf

### PR DESCRIPTION
**Pull request by pgr0ss**
fzf has a number of advantages, including:
- Faster than CtrlP, likely due to being a native binary instead of
vimscript
- No caching, so no need to refresh after files change
- Powerful, yet simple search syntax:
https://github.com/junegunn/fzf#search-syntax

The biggest change is that it opens the file window on the bottom of the
screen instead of the top. While it supposedly supports putting the
window anywhere, there's some issue with our vim/vim_dotfiles/tmux setup
that prevents it from working on top.

I would encourage people to try this out and see what they think:
```bash
cd /path/to/vim_dotfiles
git pull
git checkout alternate_fzf
vim +PlugInstall +PlugClean! +qall
(bounce existing vim instances)
```

### CODE REVIEW

**Comment by english** [comment]
I've been using `fzf` (on master) in the gateway for the past few days and have really enjoyed it. Its performance has been great but the two features I most appreciate are:

- No reloading required (I switch branches quite often)
- Flexible search syntax (in particular `'` (quote) for exact matches)

**Comment by NickTomlin** [comment]
👍 I've been playing around with this on my pair and it's fine so far.

**Comment by ctso** [comment]
My brain is trained to use the keybind <C-p>, could we also map that hotkey?

**Comment by pgr0ss** [comment]
@ctso Sounds reasonable to me: https://github.com/braintreeps/vim_dotfiles/pull/61/commits/fdff3e5df691f6373e8bdb576f59af76932a8953

**Comment by drewolson** [comment]
Yes 💯

**Comment by pgr0ss** [comment]
Per @drewolson's suggestion, I also added fuzzy searching on tags and buffers: https://github.com/braintreeps/vim_dotfiles/pull/61/commits/224b4afd1438b735fb7ea2e8cdb655ae0376fd4b. It should be strictly additive and not change the experience of anyone who has already tried out this PR.

**Comment by ssgelm** [comment]
I think we should merge this.  Once it's done I think we should get the ball rolling on merging `alternate` back into master.

**Pull request merged**
