### PR TITLE
Update fzf with version that builds for M1 macs

### PR DESCRIPTION
**Pull request by jcoleman**
# What

Update fzf with version that builds for M1 Macs.

# Why

See above.

### CODE REVIEW

**Review by ssgelm — APPROVED** [review]
Looks great. Is it worth even pinning a version at all?

**Comment by jcoleman** [comment]
@ssgelm That's a good question. Past commits have pinned it -- is that unnecessary conservatism? Or should we stick to the pattern?

**Comment by ssgelm** [comment]
I'm not sure if it's a rule per se, but my general philosophy is that it's only worth pinning if it's for a specific reason, e.g. to avoid a bug, etc.

**Comment by jcoleman** [comment]
BTW, the new version does change the appearance of fzf in Vim: (probably an improvement, to be honest, but...wanted to call it out).

Screen Shot 2022-03-27 at 9 49 46 PM

**Comment by ssgelm** [comment]
IMHO a big improvement 😄

**Comment by jcoleman** [comment]
I pushed a second commit to unpin it.

**Comment by ssgelm** [comment]
Seemed unobjectionable so I merged it

**Pull request merged**
