### PR TITLE
Include vendor in fzf

### PR DESCRIPTION
**Pull request by pgr0ss**
We vendor a lot of internal libraries and it can be very useful to search through them as well.

I encourage people to checkout this branch and see if it works for them (or if the vendor results are overpowering).

### CODE REVIEW

**Comment by marklarr** [comment]
I like this 👍

**Comment by jcoleman** [comment]
It’d be nice if there were a way to do this for only searches prefixed with `vendor/`. The gateway has so many gems it would make some queries ridiculously huge in result set.

**Comment by mrak** [comment]
This also slows down fuzzy finding in golang repos where vendored dependencies is the norm and pollutes the results.

having it only show vendor matches when the prefix is typed would be nice

**Comment by pgr0ss** [comment]
@mrak Have you experienced this slowdown or is it theoretical? Can you point me to a repo where you've experienced it (via private message)?

**Comment by ctso** [comment]
I just tried this branch out on a few golang projects that I frequent, I did not notice any slowdown at all.  I can see how this could be annoying though, I often don't care about searching those vendored dependencies. This adds thousands of files to the possible matches.

**Comment by leighmcculloch** [comment]
Is it possible to map the wider grep to a different fzf initialization, so opening it normally searches only the given project, while opening it another way will give the wider result set?

**Comment by pgr0ss** [comment]
@leighmcculloch Someone showed me that `:GFiles` should show you everything in git whereas `\ff` uses our exclusions.

**Comment by pgr0ss** [comment]
@ctso Personally, I love being able to easily jump from my code to library code when investigating an issue, so I see that as a positive. But I could be an outlier and I don't often use golang projects.

**Comment by pgr0ss** [comment]
Also, I should note that in my casual usage today, vendored stuff has shown up lower in the list (weighted partially alphabetically?) so it hasn't impacted my ability to find non-vendored things.

**Comment by leighmcculloch** [comment]
In Go code it's very easy to navigate library code by using the go to definition and list references commands instead of using fzf to try and navigate library code. Can we configure the inclusion of `vendor/` just for ruby projects, or just the dynamic languages we use, and expand that if we need it elsewhere?

This isn't impacting me personally, though and I don't feel strongly.

**Comment by pgr0ss** [comment]
@leighmcculloch I'm not sure how to do that. The fzf configured `find` seems to be global. Maybe we could move that definition into different language files? I'm not sure if it's worth it, though.

**Comment by allcentury** [comment]
In my opinion ctags are the right tool to navigate vendor'd code.  I proposed [a start to] that here https://github.com/braintreeps/vim_dotfiles/pull/85/files but in the #talk-dotfiles chatroom, it was too big of change for folks.  I'm a 👎 with this on by default.

**Comment by lollipopman** [comment]
It has always annoyed me that fzf ignored our vendor directory in infrastructure, as I often find it helpful to look at our vendored libraries, so I am all for this change, as it doesn't seem to change the speed of the tool at least in the infrastructure repo.

**Comment by pgr0ss** [comment]
It seems like people are pretty mixed on this one. Can we take a vote just to get a sense of where people stand? How about 👍 or 👎 on this comment depending on if you think we should move ahead with this change?

**Comment by NickTomlin** [comment]
I'm a soft 👎  because `vendor` casts such a wide net. I think an explicit way to either opt-in to this or trigger it manually would be best.

`<leader> fg` fuzzy finds with `:GFiles` which includes vendor results so perhaps that's an acceptable stopgap until we find a more tailored solution?

**Comment by pgr0ss** [comment]
Vote shows that this is an unfavorable change, so I'm going to close it. @NickTomlin Thanks for the pointer on `\fg`.

**Pull request closed without merging**
