### PR TITLE
Add indentation script for Groovy for better user experience

### PR DESCRIPTION
**Pull request by kcboschert**
# What

This contains the groovy indent script from:
https://github.com/vim-scripts/groovyindent-unix/blob/d6fca576272cc13fd747ff47a82b75b9e9586866/indent/groovy.vim
with a fix for labels from: https://github.com/jessfraz/.vim/blob/dc45badbe681d851d88b8be2f1be5a91790d0a99/indent/groovy.vim#L18-L20

This will do proper Groovy indentation over the default, which indents Groovy as if it were C.

We're also configuring Vim to treat all files named `Jenkinsfile` as Groovy.

# Why

Jenkinsfiles are written in Groovy, and it would be great to not have to fight our editor with indentation.

### CODE REVIEW

**Comment by pgr0ss** [comment]
Is there a reason you didn't add the repo as a new Plug? Is it because you wanted to modify it?

**Comment by kcboschert** [comment]
@pgr0ss We double-checked to see if the additional change affected what we thought, and it didn't seem to make a difference. We've switched to using the repo as a Plug.

**Comment by pgr0ss** [comment]
I haven't noticed any changes after using this branch. Can you give some examples of how this plug improves groovy indenting?

**Comment by kcboschert** [comment]
From a Jenkinsfile, subsequent lines were often indented when they should not have been:

```diff
 pipeline {
   agent none

-    environment {
-      VAR_1 = "value1"
-        VAR_2 = "value2"
-    }
+  environment {
+    VAR_1 = "value1"
+    VAR_2 = "value2"
+  }

   options {
```

Did you `:PlugInstall` or run `./activate.sh` after switching to this branch?

**Pull request merged**
